### ISSUE TITLE
Error: Invariant failed - Cypress Build Fails - 

### ISSUE THREAD

**Issue by Andrehatlo** [remix-run/indie-stack#183]
### Have you experienced this bug with the latest version of the template?

First time using this template

### Steps to Reproduce

1. Forked repo. 
2. Followed egghead.io tutorial. 
3. Pushed to github. 
4. Added SESSION_SECRET and DATABASE_URL  to Fly.io and Github. 

Works locally but building fails in Cypress on invariant:

```
node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10
        throw new Error(prefix);
              ^
Error: Invariant failed
    at invariant (/home/runner/work/remixed/remixed/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10:15)
    at getEnv (/home/runner/work/remixed/remixed/build/index.js:42:44)
   //...etc
```

### Expected Behavior

That it builds and works

### Actual Behavior

Fails on Cypress build in github.

```
> start:mocks
> binode --require ./mocks -- @remix-run/serve:remix-serve build binode ./mocks ./node_modules/dotenv/config @remix-run/serve:remix-serve build

🔶 Mock server running

/home/runner/work/remixed/remixed/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10
        throw new Error(prefix);
              ^
Error: Invariant failed
    at invariant (/home/runner/work/remixed/remixed/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10:15)
    at getEnv (/home/runner/work/remixed/remixed/build/index.js:42:44)
    at Object.<anonymous> (/home/runner/work/remixed/remixed/build/index.js:[49](https://github.com/Andrehatlo/remixed/actions/runs/3696328499/jobs/6259880586#step:9:50):14)
    at Module._compile (node:internal/modules/cjs/loader:11[55](https://github.com/Andrehatlo/remixed/actions/runs/3696328499/jobs/6259880586#step:9:56):14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:10[57](https://github.com/Andrehatlo/remixed/actions/runs/3696328499/jobs/6259880586#step:9:58):19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/runner/work/remixed/remixed/node_modules/@remix-run/serve/dist/cli.js:42:13)
http://localhost:8811 timed out on retry 91 of 3, elapsed 90307ms, limit 90000ms
Error: connect ECONNREFUSED 127.0.0.1:8811
```

**Comment by Andrehatlo** [comment]
I have checked out the other closed issues regarding `` this issue and have edited the `deploy.yml` file with the following:

github/workflows/deploy.yml
```
- name: 🌳 Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run start:mocks binode --require ./mocks --require ./node_modules/dotenv/config -- @remix-run/serve:remix-serve build
          wait-on: "http://localhost:8811"
        env:
          PORT: "8811"
```
