### ISSUE TITLE
pnpm is not preinstalled and causes an error in Cypress

### ISSUE THREAD

**Issue by hilja** [remix-run/indie-stack#212]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Follow the tutorial and push to main and let the GitHub Actions roll.

### Expected Behavior

Should go through with no errors.

### Actual Behavior

I got an error:

```
Error: Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

I needed to setup `pnpm` before Node and it worked, [detailed here](https://github.com/actions/setup-node/issues/530):

```
      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.30.3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
```

**Comment by MichaelDeBoey** [comment]
@hilja We just did some changes to the `deploy` workflow
Do you still have problems with it?

**Comment by hilja** [comment]
I migrated my app to blues-stack, but these files are pretty similar I suppose.

Just tested it with the simplified `deploy.yml` file and the Cypress action fails without these in the `deploy.yml`:

```yml
- name: ⎔ Setup pnpm
  uses: pnpm/action-setup@v2
    with:
      version: 8.3.1
```
