### ISSUE TITLE
No region defined in the fly deploy command, causes deployment to crash 

### ISSUE THREAD

**Issue by hilja** [remix-run/indie-stack#213]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Follow the tutorial and push to main, wait till the deployment step in the Actions is run.

### Expected Behavior

The deployment should go through with no errors.

### Actual Behavior

```
Error error creating a new machine machine: failed to launch VM: Mounts source volume "vol_foo" is in the wrong region ("ams" != "iad")
```

I fixed this by hardcoding `--region ams` in the deploy command:

```
      - name: 🚀 Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args: 'deploy --region ams --app ${{ steps.app_name.outputs.value }}-staging --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
```

This could be handled by the script?
